# where to put output
rootDir: "testi"
#rootDir: "/var/www/physics"

# downloaded wiki pages are cached here. NO trailing slash
cacheDir: "./sivut"

pages:
   -
      pageId: "133436923"
      pageTitle:
         fi: "Fysiikka"
         se: "Fysik - Undervisning på finska"
         en: "Physics"
      pageUrl:
         fi: "/opetus/kurssit/fysiikka"
         se: "/svenska/studierna/kurser/fysik_finska"
         en: "/english/studying/courses/physics"
   -
      pageId: "133439230"
      pageTitle:
         fi: "Ruotsinkielinen fysiikan opetus"
         se: "Fysik - Undervisning på svenska"
         en: "Physics - Teaching in Swedish"
      pageUrl:
         fi: "/opetus/kurssit/ruotsinkielinen_fysiikka"
         se: "/svenska/studierna/kurser/fysik_svenska"
         en: "/english/studying/courses/physics_swedish"
   -
      pageId: "133439202"
      pageTitle:
         fi: "Fysiikan opettajankoulutus"
         se: "Fysik lärare"
         en: "Physics teacher"
      pageUrl:
         fi: "/opetus/kurssit/fysiikan_opettajankoulutus"
         se: "/svenska/studierna/kurser/fysik_larare_undervisning"
         en: "/english/studying/courses/physics_teachers"
   -
      pageId: "133439172"
      pageTitle:
         fi: "Teoreettinen fysiikka"
         se: "Teoretisk fysik"
         en: "Theoretical physics"
      pageUrl:
         fi: "/opetus/kurssit/teoreettinen_fysiikka"
         se: "/svenska/studierna/kurser/teoretisk_fysik"
         en: "/english/studying/courses/theoretical_physics"
   -
      pageId: "133439148"
      pageTitle:
         fi: "Vesivaipan geofysiikka"
         se: "Geophysics" # TODO
         en: "Geofysik"
      pageUrl:
         fi: "/opetus/kurssit/vesivaipan_geofysiikka"
         se: "/svenska/studierna/kurser/geofysik"
         en: "/english/studying/courses/geophysics"
   -
      pageId: "133439021"
      pageTitle:
         fi: "Meteorologia"
         se: "Meteorologi"
         en: "Meteorology"
      pageUrl:
         fi: "/opetus/kurssit/meteorologia"
         se: "/svenska/studierna/kurser/meteorologi"
         en: "/english/studying/courses/meteorology"
   -
      pageId: "133439114"
      pageTitle:
         fi: "Tähtitiede"
         se: "Astronomi"
         en: "Astronomy"
      pageUrl:
         fi: "/opetus/kurssit/tahtitiede"
         se: "/svenska/studierna/kurser/astronomi"
         en: "/english/studying/courses/astronomy"

# "fetchUrl ++ pageId" is where to get the table
fetchUrl:   "https://wiki.helsinki.fi/plugins/viewsource/viewpagesrc.action?pageId="
weboodiUrl: "https://weboodi.helsinki.fi/hy/opintjakstied.jsp?html=1&Kieli="

# Column names in source table. these must align with `toLower real_col`
colCode:       "koodi" 
colLang:       "opetuskieli" 
colCourseName: "kurssin nimi" 
colRepeats:    "väli(vuosia)" 
colPeriod:     "periodi" 
colWebsite:    "kotisivu"

# kevät, kesä, syksy -- not in table but generated
colLukukausi:  "Lukukausi"

# HTML class of second column td when arranged this year
classCur: "highlight-green"

oodiNameFile: "./oodi.names"

# list of categories
categories:
   -
     - "Perusopinnot"
     - "Aineopinnot"
     - "Syventävät opinnot"
     - "Muut opinnot"
   - 
     - "1. "
     - "2. "
     - "3. "
     - "4. "
     - "5. "
     - "6. "
     - "7. "
     - "8. "
     - "9. "
   - 
     - "Pakolliset opinnot"
     - "Valinnaiset opinnot"
   -
     - "A. "
     - "B. "

languages:
   - en
   - fi
   - se

 # Internationalisation in output. Map text fragments+language pairs to
 # i18n texts
i18n:
   "Perusopinnot":
      en: "Basic studies"
      se: "Grundstudier"
   "Aineopinnot":
      en: "Intermediate studies"
      se: "Ämnesstudier"
   "Syventävät opinnot":
      en: "Advanced studies"
      se: "Advancerade studier"
   "Muut opinnot":
      en: "Other studies"
      se: "Andra studier"

   "Pakolliset opinnot":
      en: "Mandatory studies"
      se: "Obligatoriska studier"
   "Valinnaiset opinnot":
      en: "Optional studies"
      se: "Valfria studier"

   "Kaikki":
      en: "All"
      se: "Allt"
   "Kieli":
      en: "Language"
      se: "Språk"
   "Kevät":
      en: "Spring"
      se: "Vår"
   "Syksy":
      en: "Autumn"
      se: "Höst"
   "Kesä":
      en: "Summer"
      se: "Sommar"

   "koodi":
      en: "Code"
      se: "Kod"
   "kurssin nimi":
      en: "Course name"
      se: "Kursnamn"
   "periodi":
      en: "Semester"
      se: "Termin"
   "Lukukausi":
      en: "Semester"
      se: "Termin"
   "op":
      en: "ECTS"
      se: "ECTS"
   "kotisivu":
      fi: "Sivu"
      en: "Website"
      se: "Hemsida"
   "Taso":
      en: "Study level"
      se: "Level"
   "opetuskieli":
      fi: "Opetuskieli"
      en: "Language"
      se: "Språk"
   "väli(vuosia)":
      fi: "Toistuu"
      en: "Interval in years"
      se: "Intervall"

   "en":
      fi: "Englanniksi"
      en: "In English"
      se: "På engelska"
   "fi":
      fi: "Suomeksi"
      en: "In Finnish"
      se: "På finska"
   "se":
      fi: "Ruotsiksi"
      en: "In Swedish"
      se: "På svenska"

   "Päivitetty":
      fi: "Sivu päivitetty viimeksi"
      en: "Page was last updated"
      se: "Updaterad"

   "Kaikki kurssit":
      en: "All courses"
      se: "Alla kurser"

   "aputeksti":
      fi:
         >
            Klikkaa kurssikoodista WebOodiin.
            Harmaat kurssit eivät ole saatavilla tällä lukukaudella (2014-2015).
            Näiden kurssien lisäksi fysiikan laitoksella voi opiskella tiedekunnan yhteisiä opintoja, sivuaineopintoja, ja kieliopintoja jne.

            Mikäli tiedot WebOodissa eivät tyydytä, ota yhteyttä luennoitsijaan.
            Mikäli luennoitsijan sähköpostia ei löydy, ota yhteys [phyinfo@helsinki.fi](mailto:phyinfo@helsinki.fi).

            Katso opetusperiodit [täältä](http://www.physics.helsinki.fi/opetus/opetusohjelma/1415/opetusohjelma.html).
      en:
         >
            Clicking the course code goes to study guide (WebOodi).
            Courses grayed out are not available this academic year (2014-2015).
            In addition to these courses there are also faculty courses, courses in minor subjects, language courses etc.

            If information on the study guide page is not satisfactory for you, please do not hesitate to contact the lecturer.
            If lecturer email is not available, please contact [phyinfo@helsinki.fi](mailto:phyinfo@helsinki.fi).

            See dates for the periods I-IV [here](http://www.physics.helsinki.fi/opetus/opetusohjelma/1415/opetusohjelma.html).

   "1. Aerosoli- ja ympäristöfysiikka (Markku Kulmala ja Antti Lauri)":
      en: ""
      se: ""
   "1. DYNAAMINEN JA FYSIKAALINEN METEOROLOGIA":
      en: ""
      se: ""
   "2. Avaruusfysiikka (Emilia Kilpua ja Hannu Koskinen)":
      en: ""
      se: ""
   "2. MIKROMETEOROLOGIA JA KEMIALLINEN METEOROLOGIA":
      en: ""
      se: ""
   "3. Bio- lääketieteellisen fysiikka (Arto Annila ja Sauli Savolainen)":
      en: ""
      se: ""
   "4. Elektroniikka ja teollisuussovellukset (Edward Häggström)":
      en: ""
      se: ""
   "5. Hiukkas- ja ydinfysiikka ja kosmologia (Katri Huitu ja Paula Eerola)":
      en: ""
      se: ""
   "6. Laskennallinen fysiikka (Kai Nordlund ja Antti Kuronen)":
      en: ""
      se: ""
   "7. Materiaali- ja nanofysiikka (Antti Kuronen ja Mikko Hakala)":
      en: ""
      se: ""
   "8. Kiinteän maan geofysiikka (Ilmo Kukkonen ja Emilia Koivisto)":
      en: ""
      se: ""
   "A. Ydinaineksen kurssit":
      en: ""
      se: ""
   "B. Erikoistumiskurssit":
      en: ""
      se: ""
   "B. Ydinainesta täydentävät kurssit":
      en: ""
      se: ""
