pages:
   -
      pageId: "133436923"
      pageTitle:
         fi: "Fysiikka"
         se: "Fysik - Undervisning på finska"
         en: "Physics"
      pageUrl:
         fi: "/opetus/kurssit/fysiikka"
         se: "/svenska/studierna/kurser/fysik_finska"
         en: "/english/studying/courses/physics"
   -
      pageId: "133439230"
      pageTitle:
         fi: "Ruotsinkielinen fysiikan opetus"
         se: "Fysik - Undervisning på svenska"
         en: "Physics - Teaching in Swedish"
      pageUrl:
         fi: "/opetus/kurssit/ruotsinkielinen_fysiikka"
         se: "/svenska/studierna/kurser/fysik_svenska"
         en: "/english/studying/courses/physics_swedish"
   -
      pageId: "133439202"
      pageTitle:
         fi: "Fysiikan opettajankoulutus"
         se: "Fysik lärare"
         en: "Physics teacher"
      pageUrl:
         fi: "/opetus/kurssit/fysiikan_opettajankoulutus"
         se: "/svenska/studierna/kurser/fysik_lärare_undervisning"
         en: "/english/studying/courses/physics_teachers"
   -
      pageId: "133439172"
      pageTitle:
         fi: "Teoreettinen fysiikka"
         se: "Teoretisk fysik"
         en: "Theoretical physics"
      pageUrl:
         fi: "/opetus/kurssit/teoreettinen_fysiikka"
         se: "/svenska/studierna/kurser/teoretisk_fysik"
         en: "/english/studying/courses/theoretical_physics"
   -
      pageId: "133439148"
      pageTitle:
         fi: "Vesivaipan geofysiikka"
         se: "Geophysics" # TODO
         en: "Geofysik"
      pageUrl:
         fi: "/opetus/kurssit/vesivaipan_geofysiikka"
         se: "/svenska/studierna/kurser/geofysik"
         en: "/english/studying/courses/geophysics"
   -
      pageId: "133439021"
      pageTitle:
         fi: "Meteorologia"
         se: "Meteorologi"
         en: "Meteorology"
      pageUrl:
         fi: "/opetus/kurssit/meteorologia"
         se: "/svenska/studierna/kurser/meteorologi"
         en: "/english/studying/courses/meteorology"
   -
      pageId: "133439114"
      pageTitle:
         fi: "Tähtitiede"
         se: "Astronomi"
         en: "Astronomy"
      pageUrl:
         fi: "/opetus/kurssit/tahtitiede"
         se: "/svenska/studierna/kurser/astronomi"
         en: "/english/studying/courses/astronomy"

# probably needs not change; "pageUrl ++ pageId" is where to get the table
fetchUrl: "https://wiki.helsinki.fi/plugins/viewsource/viewpagesrc.action?pageId="

# Column names in source table
colCode:       "koodi" 
colLang:       "opetuskieli" 
colCourseName: "kurssin nimi" 
colRepeats:    "väli(vuosia)" 
colPeriod:     "periodi" 
colWebsite:    "kotisivu"

# TODO Not in table?
colLangFi:     "kieli-fi" 

# kevät, kesä, syksy; not in table but generated
colLukukausi:  "Lukukausi"

# HTML class of second column td when arranged this year
classCur: "highlight-green"

# list of categories
categories:
   -
     - "Perusopinnot"
     - "Aineopinnot"
     - "Syventävät opinnot"
     - "Muut opinnot"
   - 
     - "1. "
     - "2. "
     - "3. "
     - "4. "
     - "5. "
     - "6. "
     - "7. "
     - "8. "
     - "9. "
   - 
     - "Pakolliset opinnot"
     - "Valinnaiset opinnot"
   -
     - "A. "
     - "B. "

languages:
   - en
   - fi
   - se

 # Internationalisation in output. Map text fragments+language pairs to
 # i18n texts
i18n:
   "Perusopinnot":
      en: "Basic studies"
      se: "Grundstudier"
   "Aineopinnot":
      en: "Intermediate studies"
      se: "Ämnesstudier"
   "Syventävät opinnot":
      en: "Advanced studies"
      se: "Advancerade studier"
   "Muut opinnot":
      en: "Other studies"
      se: "Andra studier"

   "Kaikki":
      en: "All"
      se: "Allt"
   "Kieli":
      en: "Language"
      se: "Språk"
   "Kevät":
      en: "Spring"
      se: "Vår"
   "Syksy":
      en: "Autumn"
      se: "Höst"
   "Kesä":
      en: "Summer"
      se: "Sommar"

   "koodi":
      en: "Code"
      se: "Kod"
   "kurssin nimi":
      en: "Course name"
      se: "Kursnamn"
   "periodi":
      en: "Semester"
      se: "Termin"
   "Lukukausi":
      en: "Semester"
      se: "Termin"
   "op":
      en: "ECTS"
      se: "ECTS"
   "kotisivu":
      en: "Home page"
      se: "Hemsida"
   "Taso":
      en: "Level"
      se: "Level"
   "opetuskieli":
      fi: "Opetuskieli"
      en: "Language"
      se: "Språk"

   "väli(vuosia)":
      en: "Repeats"

   "en":
      fi: "Englanniksi"
      en: "In English"
      se: "På engelska"
   "fi":
      fi: "Suomeksi"
      en: "In Finnish"
      se: "På finska"
   "se":
      fi: "Ruotsiksi"
      en: "In Swedish"
      se: "På svenska"

   "Päivitetty":
      en: "Updated"
      se: "Updaterad"

   "Kaikki kurssit":
      en: "All courses"
      se: "Alla kurser"
   "Päivitetty":
      fi: "Viimeksi päivitetty"
      en: "Last updated"
   "aputeksti":
      fi: "Klikkaa kurssikoodista WebOodiin. Harmaat kurssit järjestetään ensi vuonna. Näiden kurssien lisäksi fysiikan laitoksella voi opiskella tiedekunnan yhteisiä opintoja, sivuaineopintoja, ja kieliopintoja jne."
      en: "Clicking the course code goes to WebOodi. Grayed courses are arranged next year. In addition to these courses there are also faculty courses, courses in minor subjects, language courses etc."
